name: Java CI/CD with Maven

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

jobs:
  set-up-environment:
    runs-on: ubuntu-latest
    outputs:
      java-home: ${{ steps.setup-java.outputs.path }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 22
        id: setup-java
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'
      - name: Verify Java version
        run: java -version
      - name: Verify Maven version
        run: mvn -version

  set-up-persistence-variables:
    needs: set-up-environment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Replace placeholders in persistence.xml
        env:
          DB_URL: ${{ secrets.DB_URL }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          sed -i 's|\${DB_URL}|'"$DB_URL"'|g' src/main/resources/META-INF/persistence.xml
          sed -i 's|\${DB_USERNAME}|'"$DB_USERNAME"'|g' src/main/resources/META-INF/persistence.xml
          sed -i 's|\${DB_PASSWORD}|'"$DB_PASSWORD"'|g' src/main/resources/META-INF/persistence.xml

  maven-life-cycles:
    needs: [set-up-environment, set-up-persistence-variables]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'
      - name: Maven Clean
        run: mvn clean -X
      - name: Maven Install
        run: mvn install -X
      - name: List target directory
        run: ls -R target
      - name: Upload War and  Report files to target directory
        uses: actions/upload-artifact@v4
        with:
          name: target-directory
          path: |
            target/*.war
            target/classes/
            target/site/
            target/jacoco-report/
            target/spotbugs.html
          if-no-files-found: error

  deploy-report-files:
    needs: maven-life-cycles
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout the report-pages branch
        uses: actions/checkout@v4
        with:
          ref: report-pages
      - name: Clean report-pages branch
        run: |
          if [ "$(git ls-files)" ]; then 
          git rm -rf .
          git clean -fdx
          else
          echo "No files to clean"
          fi
      - name: Download war and report files artifact
        uses: actions/download-artifact@v4
        with:
          name: target-directory
          path: .
      - name: List files for debugging
        run: |
          echo "Listing contents of the current directory:"
          ls -R
      - name: Set up Git
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
      - name: Add and commit reports and WAR files
        run: |
          git add .
          git commit -m "Update Reports and WAR files" || echo "No changes to commit"
      - name: Force push changes to report-pages branch
        run: git push https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git HEAD:report-pages
